('starting filling timesheet...', '05/05/2020, 15:40:57')
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    username, password = read_creds("creds.txt")
  File "main.py", line 19, in read_creds
    with open(folder_path, "r") as f:
IOError: [Errno 2] No such file or directory: 'creds.txt'
